name: Build .NET project 🏗

on: [push, pull_request]

jobs:
  buildProject:
    name: Build .NET project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Build .NET ${{ matrix.dotnet-version }} application
        run: dotnet build -c Release -o builds/${{ matrix.dotnet-version }}

      - uses: actions/upload-artifact@v2
        with:
          name: SeleniumLoadingTracker
          path: builds/${{ matrix.dotnet-version }}