name: Test Action

on:
  workflow_dispatch:
    inputs:
      tracking-points:
        description: 'Tracking points to measure'
        required: true
        default: 'Awake Start'
      warmup-runs:
        description: 'Number of warmup runs'
        required: true
        default: '2'
      measurement-runs:
        description: 'Number of measurement runs'
        required: true
        default: '10'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Assuming you have a build step that creates your WebGL build
    - name: Build WebGL
      run: |
        mkdir -p build/WebGL
        cp ExampleSite/index.html build/WebGL/
    - uses: ./
      with:
        artifact-path: build/WebGL
        port: 8080
        tracking-points: ${{ github.event.inputs.tracking-points }}
        warmup-runs: ${{ github.event.inputs.warmup-runs }}
        measurement-runs: ${{ github.event.inputs.measurement-runs }}

    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: benchmark-results.json
        retention-days: 90