name: Test Action

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to benchmark'
        required: true
        default: 'https://deml.io/experiments/unity-webgl/6000.0.27f1-webgl2'
      tracking-points:
        description: 'Tracking points to measure'
        required: true
        default: 'Awake Start'
      warmup-runs:
        description: 'Number of warmup runs'
        required: true
        default: '2'
      measurement-runs:
        description: 'Number of measurement runs'
        required: true
        default: '10'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: ./
      with:
        url: ${{ github.event.inputs.url }}
        tracking-points: ${{ github.event.inputs.tracking-points }}
        warmup-runs: ${{ github.event.inputs.warmup-runs }}
        measurement-runs: ${{ github.event.inputs.measurement-runs }}

    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: benchmark-results.json
        retention-days: 90