name: WebGL Benchmark

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to benchmark'
        required: true
        default: 'https://deml.io/experiments/unity-webgl/6000.0.27f1-webgl2'
      tracking-points:
        description: 'Tracking points to measure'
        required: true
        default: 'Awake Start'
      warmup-runs:
        description: 'Number of warmup runs'
        required: true
        default: '2'
      measurement-runs:
        description: 'Number of measurement runs'
        required: true
        default: '10'

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Build project
      run: dotnet build SeleniumLoadingTracker/SeleniumLoadingTracker.csproj

    - name: Run benchmark
      run: |
        dotnet run --project SeleniumLoadingTracker/SeleniumLoadingTracker.csproj -- \
          --url "${{ github.event.inputs.url }}" \
          --tracking-points "${{ github.event.inputs.tracking-points }}" \
          --warmup-runs ${{ github.event.inputs.warmup-runs }} \
          --measurement-runs ${{ github.event.inputs.measurement-runs }} \
          --headless true

    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: benchmark-results.json
        retention-days: 90